articleBoard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls'), name='board_app'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/urls.py
from django.urls import path
from .views import AdFiltered, AdList, AdDetail, AdCreate, AdEdit, AdDelete,\
    ReplyCreate, ReplyDelete, ReplyConfirmApprove, ReplyList, approve_reply,\
    NewsList, NewsDetail, NewsCreate, NewsEdit, NewsDelete, news_subscribe,\
    news_unsubscribe, NewsMailingConfirm, news_mailing_confirm

urlpatterns = [
    path('ad', AdList.as_view(), name='ad_list_view'),
    path('ad/<int:pk>', AdDetail.as_view(), name='ad_detail_view'),
    path('ad/create', AdCreate.as_view(), name='ad_create_view'),
    path('ad/<int:pk>/edit', AdEdit.as_view(), name='ad_edit_view'),
    path('ad/<int:pk>/delete', AdDelete.as_view(), name='ad_delete_view'),
    path('ad/filtered', AdFiltered.as_view(), name='ad_filtered_view'),
    path('reply', ReplyList.as_view(), name='reply_list_view'),
    path('reply/<int:ad_id>/create', ReplyCreate.as_view(),
         name='reply_create_view'),
    path('reply/<int:pk>/delete', ReplyDelete.as_view(),
         name='reply_delete_view'),
    path('reply/<int:pk>/approve', ReplyConfirmApprove.as_view(),
         name='reply_approve_view'),
    path('reply/<int:pk>/approve_confirm', approve_reply,
         name='reply_approve_button'),
    path('news', NewsList.as_view(), name='news_list_view'),
    path('news/<int:pk>', NewsDetail.as_view(), name='news_detail_view'),
    path('news/create', NewsCreate.as_view(), name='news_create_view'),
    path('news/<int:pk>/edit', NewsEdit.as_view(), name='news_edit_view'),
    path('news/<int:pk>/delete', NewsDelete.as_view(),
         name='news_delete_view'),
    path('news/subscribe', news_subscribe, name='news_subscribe_button'),
    path('news/unsubscribe', news_unsubscribe, name='news_unsubscribe_button'),
    path('news/<int:pk>/mailing', NewsMailingConfirm.as_view(),
         name='news_confirm_mailing_view'),
    path('news/<int:pk>/mailing_confirm', news_mailing_confirm,
         name='news_confirm_mailing_button'),
]

board/models.py
from django.db import models
from django.contrib import auth

from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Ad(models.Model):
    user_id = models.ForeignKey(auth.get_user_model(),
                                on_delete=models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE,
                                    verbose_name='Категория')
    header = models.CharField(max_length=255, verbose_name='Заголовок')
    ad = RichTextUploadingField(default='', verbose_name='Объявление')
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.header

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Reply(models.Model):
    user_id = models.ForeignKey(auth.get_user_model(),
                                on_delete=models.CASCADE)
    ad_id = models.ForeignKey(Ad, on_delete=models.CASCADE)
    reply = models.TextField(default='', verbose_name='Отклик')
    creation_time = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.reply

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'


class News(models.Model):
    user_id = models.ForeignKey(auth.get_user_model(),
                                on_delete=models.CASCADE)
    header = models.CharField(max_length=255, verbose_name='Заголовок')
    news = RichTextUploadingField(default='', verbose_name='Новость')
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.header

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


def return_user_email(user):
    return user.email

templates/ad_create.html
{% extends 'flatpages/default.html' %}
{% load static %}

{% block head_title %}
Объявление
{% endblock head_title %}

{% block body %}
    <h1>Редактирование объявления</h1>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Сохранить изменения">
    </form>
{% endblock body %}

templates/ad_delete.html
{% extends 'flatpages/default.html' %}

{% block head_title %}
Удаление объявления
{% endblock head_title %}

{% block body %}
    <h1>Вы уверены, что хотите удалить объявление?</h1>
    <hr>
    <table>
        <thead>
            <tr>
                <td>
                    Категория
                </td>
                <td>
                    Время создания
                </td>
                <td>
                    Заголовок
                </td>
                <td>
                    Объявление
                </td>
            </tr>
        </thead>
        <tr>
            <td>
                {{ ad_delete.category_id }}
            </td>
            <td>
                {{ ad_delete.creation_time|date:'d.m.Y G:i' }}
            </td>
            <td>
                {{ ad_delete.header|truncatechars:50 }}
            </td>
            <td>
                {{ ad_delete.ad|striptags|truncatewords:20 }}
            </td>
        </tr>
    </table>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Подтвердить">
    </form>
{% endblock body %}

templates/ad_detail.html
{% extends 'flatpages/default.html' %}

{% load account %}

{% block head_title %}
Объявление
{% endblock head_title %}

{% block body %}
    <h1>{{ ad.header }}</h1>

    <h5>{{ ad.category_id }}</h5>

    <h6>{{ ad.creation_time|date:'d.m.Y G:i' }}</h6>
    <p>{{ ad.ad|safe }}</p>
    <h6>Автор: {{ ad.user_id.email }}</h6>
    {% if user.is_authenticated %}
        <div>
            <button><a href="{% url 'reply_create_view' ad.id %}">Отозваться</a></button>
            {% if user.id == ad.user_id.id %}
                <button><a href="{% url 'ad_edit_view' ad.id %}">Редактировать</a></button>
                <button><a href="{% url 'ad_delete_view' ad.id %}">Удалить</a></button>
            {% endif %}
        </div>
    {% endif %}
    <hr>

{% endblock body %}

templates/ad_filtered.html
{% extends 'flatpages/default.html' %}

{% block title %}
Отклики на мои объявления
{% endblock title %}

{% block head_title %}
Отклики на мои объявления
{% endblock head_title %}

{% block body %}
    <h1>Отклики на мои объявления</h1>

    <h2>Фильтр по объявлениям</h2>
    <form method="GET">
        {{ filter.form.as_p }}
        <input type="submit" value="Найти">
    </form>
    <hr>

    {% if page_obj %}
        {% comment %} {% for ad in page_obj %}
            <h3>
                <a href="{% url 'ad_detail_view' ad.id %}">{{ ad.header|truncatechars:50 }}</a>
            </h3>
            <p>
                {{ ad.category_id }}
            </p>
            <p>
                {{ ad.creation_time|date:'d.m.Y G:i' }}
            </p>
            <p>
                {{ ad.ad|striptags|truncatewords:70 }}
            </p>

            {% if reply_list %}
                <table>
                {% for reply in reply_list %}
                    {% if reply.ad_id.id == ad.id %}
                        <tr>
                            <td>
                                {% if not reply.is_approved %}
                                    <div>
                                        <button><a href="{% url 'reply_approve_view' reply.id %}">Подтвердить</a></button>
                                    </div>
                                {% endif %}
                            </td>
                            <td>
                                {{ reply.user_id.email }}
                            </td>
                            <td>
                                {{ reply.creation_time }}
                            </td>
                            <td>
                                {{ reply.reply }}
                            </td>
                            <td>
                                {% if not reply.is_approved %}
                                    <div>
                                        <button><a href="{% url 'reply_delete_view' reply.id %}">Удалить</a></button>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </table>
            {% endif %}
            <hr>
        {% endfor %} {% endcomment %}
        {% for ad in page_obj %}
            {% if ad.reply__is_approved != None %}
                <h5>
                    Отклик
                </h5>
                <p>
                    {{ ad.reply__user_id__email }}
                    {{ ad.reply__creation_time }}
                </p>
                <p>
                    {{ ad.reply__reply }}
                </p>
                {% if not ad.reply__is_approved %}
                    <p> <b>Статус:</b>
                        <div>
                            <button><a href="{% url 'reply_approve_view' ad.reply__id %}">Подтвердить</a></button>
                            <button><a href="{% url 'reply_delete_view' ad.reply__id %}">Удалить</a></button>
                        </div>
                    </p>
                {% else %}
                    <p> <b>Статус:</b>
                        Подтвержден
                    </p>
                {% endif %}
            {% else %}
                <h5>
                    Нет откликов
                </h5>
            {% endif %}
            <h5>
                Для объявления
            </h5>
            <p>
                {{ ad.category_id__name }}
                {{ ad.creation_time|date:'d.m.Y G:i' }}
                {{ ad.user_id__email }}
            </p>
            <h6>
                <a href="{% url 'ad_detail_view' ad.id %}">{{ ad.header }}</a>
            </h6>
            <p>
                {{ ad.ad|striptags|truncatewords:30 }}
            </p>
            <hr>
            {% comment %} <h5>
                Объявление
            </h5>
            <h4>
                <a href="{% url 'ad_detail_view' reply.ad_id.id %}">{{ reply.ad_id.header|truncatechars:50 }}</a>
            </h4>
            <p>
                {{ reply.ad_id.category_id }}
                {{ reply.ad_id.creation_time|date:'d.m.Y G:i' }}
                {{ reply.ad_id.user_id.email }}
            </p>
            <p>
                {{ reply.ad_id.ad|striptags|truncatewords:70 }}
            </p>
            <h5>
                Отзыв
            </h5>
            {% if not reply.is_approved %}
                <p>
                    <div>
                        <button><a href="{% url 'reply_approve_view' reply.id %}">Подтвердить</a></button>
                    </div>
                </p>
            {% endif %}
            <p>
                {{ reply.user_id.email }}
                {{ reply.creation_time }}
            </p>
            <p>
                {{ reply.reply }}
            </p>
            <p>
                {% if not reply.is_approved %}
                    <div>
                        <button><a href="{% url 'reply_delete_view' reply.id %}">Удалить</a></button>
                    </div>
                {% endif %}
            </p>
            <hr> {% endcomment %}
        {% endfor %}
        {% block paginator %}
            {{ block.super }}
        {% endblock paginator %}
    {% else %}
        <h2>Нет откликов и объявлений!</h2>
    {% endif %}

{% endblock body %}

templates/ad_list.html
{% extends 'flatpages/default.html' %}

{% load url_filters %}

{% block head_title %}
Все объявления
{% endblock head_title %}

{% block body %}
    <h1>Все объявления</h1>
    <hr>

    {% if page_obj %}
        <table style='width: 100%'>
            <thead>
                <tr>
                    <td style='width: 10%'>
                        Время создания
                    </td>
                    <td style='width: 10%'>
                        Категория
                    </td>
                    <td style='width: 15%'>
                        Заголовок
                    </td>
                    <td style='width: 55%'>
                        Объявление
                    </td>
                    <td style='width: 10%'>
                        Автор
                    </td>
                </tr>
            </thead>
            {% for ad in page_obj %}
                <tr>
                    <td>
                        {{ ad.creation_time|date:'d.m.Y G:i' }}
                    </td>
                    <td>
                        {{ ad.category_id }}
                    </td>
                    <td>
                        <a href="{% url 'ad_detail_view' ad.id %}">{{ ad.header|truncatechars:50 }}</a>
                    </td>
                    <td>
                        {{ ad.ad|striptags|truncatewords:20 }}
                    </td>
                    <td>
                        {{ ad.user_id.email }}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% block paginator %}
            {{ block.super }}
        {% endblock paginator %}
    {% else %}
        <h2>Нет объявлений!</h2>
    {% endif %}

{% endblock body %}

templates/news_confirm_mailing.html
{% extends 'news_detail.html' %}

{% load account %}

{% block head_title %}
Подтвердить рассылку
{% endblock head_title %}

{% block body %}
    <p>Вы действительно хотите разослать эту новость?</p>
    <hr>
    {% block body_top %}
        {% if perms.board.create_news %}
            <div>
                <button><a href="{% url 'news_confirm_mailing_button' news.id %}">Разослать</a></button>
            </div>
        {% endif %}
    {% endblock body_top %}
    {% block body_news %}
        {{ block.super }}
    {% endblock body_news %}
{% endblock body %}

templates/news_create.html
{% extends 'flatpages/default.html' %}
{% load static %}

{% block head_title %}
Новость
{% endblock head_title %}

{% block body %}
    <h1>Редактирование новости</h1>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" value="Сохранить изменения">
    </form>
{% endblock body %}

templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block head_title %}
Удаление новости
{% endblock head_title %}

{% block body %}
    <h1>Вы уверены, что хотите удалить эту новость?</h1>
    <hr>
    <table>
        <thead>
            <tr>
                <td>
                    Время создания
                </td>
                <td>
                    Заголовок
                </td>
                <td>
                    Новость
                </td>
            </tr>
        </thead>
        <tr>
            <td>
                {{ news_delete.creation_time|date:'d.m.Y G:i' }}
            </td>
            <td>
                {{ news_delete.header|truncatechars:50 }}
            </td>
            <td>
                {{ news_delete.news|striptags|truncatewords:20 }}
            </td>
        </tr>
    </table>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Подтвердить">
    </form>
{% endblock body %}

templates/news_detail.html
{% extends 'flatpages/default.html' %}

{% load account %}

{% block head_title %}
Новость
{% endblock head_title %}

{% block body %}
    <hr>
    {% block body_top %}
        {% if perms.board.change_news %}
            <div>
                <button><a href="{% url 'news_edit_view' news.id %}">Редактировать</a></button>
            </div>
        {% endif %}
        {% if perms.board.delete_news %}
            <div>
                <button><a href="{% url 'news_delete_view' news.id %}">Удалить</a></button>
            </div>
        {% endif %}
        {% if perms.board.create_news %}
            <div>
                <button><a href="{% url 'news_confirm_mailing_view' news.id %}">Разослать</a></button>
            </div>
        {% endif %}
    {% endblock body_top %}
    {% block body_news %}
        <h1>{{ news.header }}</h1>

        <h6>{{ news.creation_time|date:'d.m.Y G:i' }}</h6>
        <p>{{ news.news|safe }}</p>
        <h6>Автор: {{ news.user_id.email }}</h6>
        <hr>
    {% endblock body_news %}

{% endblock body %}

templates/news_list.html
{% extends 'flatpages/default.html' %}
{% load account %}
{% load url_filters %}

{% block head_title %}
Все новости
{% endblock head_title %}

{% block body %}
    <h1>Все новости</h1>
    {% if user.is_authenticated %}
        {% if in_mailing_list %}
            <div>
                <button><a href="{% url 'news_unsubscribe_button' %}">Отписаться от рассылки новостей</a></button>
            </div>
        {% else %}
            <div>
                <button><a href="{% url 'news_subscribe_button' %}">Подписаться на рассылку новостей</a></button>
            </div>
        {% endif %}
    {% endif %}
    <hr>
    {% if page_obj %}
        {% for news in page_obj %}
            <h5>
                <a href="{% url 'news_detail_view' news.id %}">{{ news.header }}</a>
            </h5>
            <p>
                {{ news.creation_time|date:'d.m.Y G:i' }}
                автор: {{ news.user_id.email }}
            </p>
            <p>
                {{ news.news|striptags|truncatewords:60 }}
            </p>
            <hr>
        {% endfor %}
        {% block paginator %}
            {{ block.super }}
        {% endblock paginator %}
    {% else %}
        <h2>Нет новостей!</h2>
    {% endif %}

{% endblock body %}

templates/reply_approve.html
{% extends 'flatpages/default.html' %}

{% load account %}

{% block head_title %}
Подтвердить отклик
{% endblock head_title %}

{% block body %}
    <h1>Вы уверены, что хотите подтвердить отклик на ваше объявление?</h1>
    <h6>{{ reply.creation_time|date:'d.m.Y G:i' }}</h6>
    <p>{{ reply.reply }}</p>
    <h6>Автор: {{ reply.user_id.email }}</h6>
    {% if user.is_authenticated %}
        {% if user.id == reply.ad_id.user_id.id %}
            <div>
                <button><a href="{% url 'reply_approve_button' reply.id %}">Подтвердить</a></button>
            </div>
        {% endif %}
    {% endif %}
    <hr>

    <h2>Объявление</h2>
    <h3>{{ reply.ad_id.header }}</h3>
    <h3>Автор: {{ reply.ad_id.user_id.email }}</h3>
    <h6>{{ reply.ad_id.creation_time|date:'d.m.Y G:i' }}</h6>
    <p>{{ reply.ad_id.ad|safe }}</p>

{% endblock body %}

templates/reply_create.html
{% extends 'flatpages/default.html' %}
{% load static %}

{% block head_title %}
Отклик
{% endblock head_title %}

{% block body %}
    <h1>Редактирование отклика</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить изменения">
    </form>
{% endblock body %}

templates/reply_delete.html
{% extends 'flatpages/default.html' %}

{% block head_title %}
Удаление отклика
{% endblock head_title %}

{% block body %}
    <h1>Вы уверены, что хотите удалить отклик?</h1>
    <hr>
    <p>{{ reply_delete.creation_time|date:'d.m.Y G:i' }}</p>
    <p>{{ reply_delete.reply }}</p>
    <p>{{ reply_delete.user_id.email }}</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Подтвердить">
    </form>
    <hr>
    <p>Объявление:</p>
    <p><a href="{% url 'ad_detail_view' reply_delete.ad_id.id %}">{{ reply_delete.ad_id.header }}</a></p>
{% endblock body %}

templates/reply_list.html
{% extends 'flatpages/default.html' %}

{% load url_filters %}

{% block head_title %}
Мои отклики
{% endblock head_title %}

{% block body %}
    <h1>Мои отклики</h1>
    <hr>

    {% if page_obj %}
        <table style='width: 100%'>
            <thead>
                <tr>
                    <td style='width: 10%'>
                        Время создания
                    </td>
                    <td style='width: 10%'>
                        Статус
                    </td>
                    <td style='width: 60%'>
                        Отзыв
                    </td>
                    <td style='width: 20%'>
                        Объявление
                    </td>
                </tr>
            </thead>
                {% for reply in page_obj %}
                    <tr>
                        <td>
                            {{ reply.creation_time|date:'d.m.Y G:i' }}
                        </td>
                        <td>
                            {{ reply.is_approved|yesno:'Подтвержден,На рассмотрении'}}
                        </td>
                        <td>
                            {{ reply.reply }}
                        </td>
                        <td>
                            <a href="{% url 'ad_detail_view' reply.ad_id.id %}">{{ reply.ad_id.header }}</a>
                        </td>
                    </tr>
                {% endfor %}
        </table>
        {% block paginator %}
            {{ block.super }}
        {% endblock paginator %}
    {% else %}
        <h2>Нет откликов!</h2>
    {% endif %}

{% endblock body %}